name = "DifferentialGeometry"
version = "0.1.2"
keywords = ["math"]
defaultTargets = ["DifferentialGeometry"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true
linter.style.header = false
linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "769b0a5ad45c8d886c754c0be19835b908f98dcb"

[[lean_lib]]
name = "DifferentialGeometry"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "HamiltonDefinitions"
